### ISSUE TITLE
DNS for sst-simulator.org needs to be redirected to sstsimulator.github.io

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-sqe#102]
sstsimulator.github.io is the new website for sst simulator project.  Currently the url sst-simulator.org is pointing to the old trac based wiki.  The DNS for the url must be changed to point to the new website.

**Comment by nmhamster** [comment]
Sue is going to look into this on Monday for us.

**Comment by allevin** [comment]
This has been done, but the change on the DNS is just a straight forward of the URL to sstsimulator.github.io.  The only problem is that after the forward, the URL in the browser says "sstsimulator.github.io"  instead of "sst-simulator.org".  This is a minor but annoying issue.

Reading the GitHub Pages documentation, if we change the DNS CNAME record to point to sstsimulator.github.io (and make a file change to the project), we can have the url shown in the browser show sst-simulator.org.  

This may be something we want to investigate.

**Comment by allevin** [comment]
The DNS has been changed, and now when browsing sst-simulator.org the url says sst-simulator.org not sstsimulator.github.io.
