### ISSUE TITLE
Running ldd and otool -L to find sstsim.x seems broke

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-sqe#1069]
On one of the Mac builds that completed successfully (I saw a linux build that used ldd and also failed) What is going on here.
```
17:38:16 $ ldd ./src/sst/core/sstsim.x
17:38:16 ldd: ./src/sst/core/sstsim.x: No such file or directory
17:38:16 SST-CORE BUILD INFO============================================================
```

**Comment by berquist** [comment]
Commands returning non-zero error codes (like the one shown) were not universally trapped until https://github.com/sstsimulator/sst-sqe/pull/1094.  At this point there's no way I can tell why that path wasn't available, but now an error like that will always fail the build.
