### ISSUE TITLE
Nightly Status Email Bug with Failed Builds

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-sqe#129]
In the email from 25th Feb 2016, the Ubuntu build failed but the marking is TESTFAIL when it should be FAILED.
```
TESTFAIL : SST__COE_RHEL_7_OMPI-1.10_Boost-1.56_mainline

PASSED : SST__memH_using_Ariel

TESTFAIL : SST__Ubuntu_16.04B_OMPI_1.6.5_Boost_1.56_mainline

TESTFAIL : SST__x-Multithread-MacOS-n2

TESTFAIL : SST__x-Multithread-Ubuntu-n2
```

But further below:

```
FAILED : Job SST__Ubuntu_16.04B_OMPI_1.6.5_Boost_1.56_mainline: Build # 36
Job - Is Running: False
Job - Is Good: False
Job - Status: FAILURE
Job - Duration: 0:28:05.475000
```

**Comment by allevin** [comment]
From Si...

Sorry that’s me not being clear in the email and putting two thoughts in
one sentence. The first part of that is asking whether we can detect a
build fail separately from a test fail. I’m a bit worried the red will
make the FAILED test that sits on the top of it unreadable. Can we pick
HTML color values for these labels or are they named colors?

What we want is:

- PASS - Green - compiles and passes correctly
- TESTFAIL - Orange - compiles but fails testing
- FAILED - Red - doesn’t compile

**Comment by allevin** [comment]
Let me look into it.  Jenkins reports a “failed to compile" as a failure, but I might be able to extract some additional information that can do what you are suggesting.

**Comment by nmhamster** [comment]
I think just having compile failure separated out from test failure in the color scheme would be helpful.

**Comment by allevin** [comment]
The output has been changed, failure to compile/run sst will be marked as "FAILED" in red, and failure during testing will be marked as "TESTFAIL" in orange.  However the summary at the email top will show a summation of all failures.
