### ISSUE TITLE
Nightly build on Ubuntu 16.04 fails due to module initialization issue.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#130]
Latest Ubuntu update seem to have altered something with non-login module initialization.

The Jenkins runs are no longer loading modules.    Build failure come from needing Boost-1.56

**Comment by allevin** [comment]
From J. Wilson

This fix would be to source /etc/profile.d/modules.sh (if it exists and is executable) prior to invoking the “module” command.  That is,

if [ -x /etc/profile.d/modules.sh ]
then
    source /etc/profile.d/modules.sh 
fi

I’m going to file a bug report against this on Ubuntu so that they can try to fix it before release of 16.04.

**Comment by allevin** [comment]
Propose for a quick and dirty workaround, that we execute the script above in the "Execute Shell" section in the Jenkins job.  This might temporarily fix the issue until Ubuntu can correct the issue.

**Comment by jpvandy** [comment]
Do we need to restrict it to Ubuntu 16.04 ?

**Comment by allevin** [comment]
Yes, this is only a quick and dirty workaround (assuming it works) for the issue with Ubuntu 16.04.  Hopefully the bug report that Jon is writing against Ubuntu 16.04 will be fixed and we can remove our change from the Jenkins project.

**Comment by jwilso** [comment]
This has been reported to Ubuntu as Bug #1549903.

J.

--
Jon Wilson
SST Software Engineering/Quality Assurance
CSRI
Sandia National Laboratories

**Comment by jwilso** [comment]
Change the [ -x ...] to [ -r ...]

The file should be sourced.

J.

--
Jon Wilson
SST Software Engineering/Quality Assurance
CSRI
Sandia National Laboratories

**Comment by jwilso** [comment]
Issue against beta version of Ubuntu (16.04B).  Resolved in final release version of 16.04.
