### ISSUE TITLE
openmpi is leaving around empty directories on /tmp

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#149]
On sst=test, Gwen has less than 5000,   jpvandy has more than 15,000 and jwilson has over 30,000.

(they are in subdirectories by user, so the number shown by "ls /tmp"  is not large.)

The needed clean-up may well be other than in SQE

**Comment by jpvandy** [comment]
Should determine if the recent core upgrade to (beffer?) process destructors relieves this problem..

**Comment by allevin** [comment]
@jwilso I don't believe this is a problem anymore... Can we close this issue?
