### ISSUE TITLE
running "mpirun -np 2", two miranda tests time limit

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#165]
Have not yet tried a major increase in time limit to see if they eventually finish.

miranda_singlestream  went time limit at 200 seconds.   (without multithread - 6 sec/ n=2 - 43 sec)

miranda_randomgen went time limit at nearly an hour, 3500 seconds. (w/o mt 130 sec/ n=2 - 495)

**Comment by nmhamster** [comment]
@jpvandy thinks we are not running these tests currently on multi-rank. Need to check?

**Comment by jpvandy** [comment]
@nmhamster : These two tests are not being run either multi-Thread or multi-Rank from the SQE Miranda Suite.    Should this be retested?
@feldergast : Rational was, these tests "use an event that doesn't implement serialization."

**Comment by jpvandy** [comment]
Not much has changed.
2x2 has been run on sst-test and El Capitan for the single stream tests    180 seconds and 352 seconds respectively.   Not enabled in the nightly testing for any multi tests
@nmhamster

**Comment by allevin** [comment]
Transferred this issue to SST-Elements issue 1594
