### ISSUE TITLE
Testing needs generic solution to case with a file per rank.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#220]
So far for tests that fail, because one file is expected and Multi-Rank spreads the output over a file per rank, individual Suites have had specific solutions inserted.   Until memHSieve, these were all on stdout.

A subroutine, or Macro needs to be created to handle these cases, instead of spreading unique point solutions over the testSuites.

**Comment by allevin** [comment]
This issue is overtaken by the new test frameworks - closing
