### ISSUE TITLE
Need an automated Valgrind check against as many different sst tests as reasonable.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#228]
Si has previously requested automated Valgrind testing.
The number of "one-time-only" failures in the Nightly testing being seen means that ways to pursue validation is need as a way to attack tests failures that a simple rerun does not reproduce.

**Comment by nmhamster** [comment]
We also have the option of using Intel Inspector XE for Intel-based Linux systems. This is a bit faster and can pick up a lot of bugs (memory leaks, thread races etc). Perhaps we could use this on `sst-test` for some subset of the test suite?

**Comment by jpvandy** [comment]
For a number of months we have been running weekly automated Valgrind tests.   Of the 79 tests plus 180 Ember Sweep tests only hybridSim and Qsim do not run clean.

**Comment by jpvandy** [comment]
Currently, Valgrind is also generating complaints on Ariel ivy bridge and sandy bridge tests and from from memHierarchy-sdl tests.
 
I am going to close this issue and open a new issue in the sst-elements repository
