### ISSUE TITLE
The Ariel test Suite fails except on sst-test, because of faulty testing input.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#302]
The Sandy-bridge and Ivy-bridge tests were created using an existing static binary test object.  That binary was created in 2014 (or before) on sst-test.   It was built using pthreads download from m5threads.   The binary object is still processed by Ariel seemingly happily on sst-test.   The Ariel processing of it fails on Ubuntu 14.04.  (The four other in the Suite, which are believed to pass, use a locally built stream object.)
@gvoskuilen:   @nmhamster

**Comment by nmhamster** [comment]
This is fixed by using compiled binary (on platform) but tests now take longer.
