### ISSUE TITLE
Not testing with --disable-mpi

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-sqe#315]
None of our test builds use '--disable-mpi'.   That build mechanism should probably be tested.

**Comment by jpvandy** [comment]
Nightly tests now running on Linux (sst-test) and Mac (El Capitan).
(No changes needed to SST.   A few details had to be adjusted in the testing harness.)

**Comment by jpvandy** [comment]
Test has been running in the nightly on two platforms for three months
