### ISSUE TITLE
Daily Report Summary has an Name Error on Mac Builds

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-sqe#318]
I am seeing:

```
ERROR : SST__OutOfSource_MacOSX_10.10.5_OMPI_1.8_Boost_1.56_clang_700.1.81_mainline
```

This seems to be a name mis-match in configuration for email.

**Comment by allevin** [comment]
I saw it,

I think John changed the name of the Jenkins job and the nightly report is looking for the old name.  I will fix it in a while.  The job (with the new name) did pass overnight.

--
Aaron

**Comment by nmhamster** [comment]
@allevin thanks. Is the configuration for this one online or is it local only?

**Comment by allevin** [comment]
The change is to the sst-autotesting/nightlyreportgen.cfg file.  We just need to change entry in GitHub.  The tool automatically downloads the cfg file and uses the latest.

**Comment by allevin** [comment]
sst-autotesting/nightlyreportgen.cfg has been changed.  Nightly reports should now be correct.  This issue can be closed after error is confirmed to be removed from report.

**Comment by nmhamster** [comment]
@allevin thanks for getting to this so quickly. I'll check report in the morning.

**Comment by jpvandy** [comment]
As noted, this was promptly fixed.
