### ISSUE TITLE
Ubuntu 14.04  fails configure since the Jenkins and VM upgrades

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#343]
I will attempt to attach the log file from the Ubuntu mainline run #296
[Ubuntu.on.Jenkins.txt](https://github.com/sstsimulator/sst-sqe/files/384711/Ubuntu.on.Jenkins.txt)

**Comment by jwilso** [comment]
No upgrades were performed on Ubuntu 14.04, it is the same configuration as previous successful runs.

Modules is not available to modules wrapper moduleex.sh.  Modules must be initialized first before usage.

--------------------PRE-BUILD ENVIRONMENT VARIABLE DUMP--------------------
--------------------modules status--------------------
/home/sstbuild/jenkins/workspace/SST__Ubuntu_14.04_OMPI_1.8_Boost_1.56_mainline/296_296/devel/trunk/test/utilities/moduleex.sh: line 26: module: command not found
/home/sstbuild/jenkins/workspace/SST__Ubuntu_14.04_OMPI_1.8_Boost_1.56_mainline/296_296/devel/trunk/test/utilities/moduleex.sh: line 26: module: command not found
--------------------modules status--------------------
==================== Building SST CORE ====================
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
bamboo.sh: running "autogen.sh" on SST-CORE...

**Comment by jpvandy** [comment]
Aaron adapted the utility moduleex to initialize modules from the new location of modules after the upgrade.
