### ISSUE TITLE
Need better detection of test Suites failures.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#407]
This is about a failure in the test Suite, not a failure in an individual test.   The output for Jenkins is not generated until an individual test actually runs.

If a test Suite fails in an unanticipated manner, Jenkins likely doesn't detect it and so it's not flagged in the Summary records.   It simply vanishes from the list of executed tests.

(When testing our test process on Out-of-Source build and denying write permission to the source, at least, 5 test Suites failed and silently vanished from the list.)

**Comment by jpvandy** [comment]
More data:   While making the label ES consistent and removing SE in EmberSweep, the change needed in a python file was omitted.  When it was tested:
It is significant to note, that on various Projects, all 180 ember Sweep tests failed, but Jenkins reported that they passed.   We do not employ a positive message to shunit2 that a test passed.   We only notify of a failure and if we skip that call to ASSERT, the test passes.

**Comment by allevin** [comment]
This issue is overtaken by the new test frameworks - closing
