### ISSUE TITLE
Auto tester does not detect errors unique to out-of-source build

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#419]
Testing this may be more expensive, than it merits.   This would likely require an addition test Project because the variable is the actual build.

(A change that only broke out-of-source build did get auto-merged this month.)

**Comment by allevin** [comment]
Two autotester projects in Jenkins for 1) SST-Macro and 2) SST-Elements/SST-Core have been changed to turn on the out of source build flag.  This will now perform one of the autotester build and tests as out of source.
