### ISSUE TITLE
Move SQE reference files to Elements

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-sqe#447]
Currently most reference files for Elements are located in the sst-sqe repo.  This introduces a synchronization issue for the Auto-Tester as necessary changes to an element in repo sst-elements that changes its output will fail tests until the reference file in sst-sqe is changed.

Suggest that we move the reference files under the test directory for each specific element.  Then (usually) only changes to the sst-element repo will be required.

**Comment by jpvandy** [comment]
memH sdl  and memHA have been moved   to   memHierarchy/tests/refFiles 

@gvoskuilen

**Comment by jpvandy** [comment]
Almost all tests in the nightly are now believed to be running using reference files in the elements directory.   "Almost" because there are two tests that are not related to a component repository, Hybridsim and check_maxrss.
