### ISSUE TITLE
Time Limit processer on El Capitan failed to terminate memHSieve test.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#496]
Time limit processing is different between Linux and El Capitan.

Time Limit processor left job running (until manually killed) with a memHSieve test on 6.1 release branch on El Capitan.

TL Enforcer:            TIME LIMIT     test_memHSieve 
TL Enforcer: test has exceed alloted time of 50 seconds.
         Create Time Limit Flag file, /tmp/TimeFlag_40708_41063
 
I am 41063, I was called from 40708, my parent PID is 41016
  UID   PID  PPID   C STIME   TTY           TIME CMD
  502 40708 51283   0  2:40AM ??         0:00.01 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
  502 41016 40708   0  2:40AM ??         0:00.02 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
 
  502 41072 41068   0  2:40AM ??         0:00.03 /usr/local/module-pkgs/pin/pin-2.14-71313-clang.5.1-mac/intel64/bin/pinbin -p32 /usr/local/module-pkgs/pin/pin-2.14-71313-clang.5.1-mac/ia32/bin/pinbin -sigchld_handler 1 -follow_execv -t /Users/sstbuild/jenkins/workspace/SST__6.1.0_beta_OutOfSource_MacOSX_10.11_OMPI_1.8_Boost_1.56_clang_700.1.76_mainline/20_20/local/sst-elements/libexec/fesimple.dylib -p /sst_shmem_41068-0-16807 -v 1 -t 0 -i 1000000000 -c 16 -s 1 -m 1 -k 1 -d 0 -- ./ompsievetest
  502 41187 41072   0  2:41AM ??         0:11.06 ./ompsievetest
  502 41301 41259   0  2:41AM ??         0:00.03 /usr/local/module-pkgs/pin/pin-2.14-71313-clang.5.1-mac/intel64/bin/pinbin -p32 /usr/local/module-pkgs/pin/pin-2.14-71313-clang.5.1-mac/ia32/bin/pinbin -sigchld_handler 1 -follow_execv -t /Users/sstbuild/jenkins/workspace/SST__Nightly_OutOfSource_MacOSX_10.11_OMPI_1.8_Boost_1.56_clang_700.1.76_mainline/221_221/local/sst-elements/libexec/fesimple.dylib -p /sst_shmem_41259-0-16807 -v 1 -t 0 -i 1000000000 -c 16 -s 1 -m 1 -k 1 -d 0 -- ./ompsievetest
  502 41304 41301   0  2:41AM ??         0:11.15 ./ompsievetest
  502 41413 41063   0  2:41AM ??         0:00.00 grep ompsievetest
 this might better go in the Suite
Identified routine: gettimeofday, replacing with Ariel equivalent...
Replacement complete.
Identified routine: malloc/_malloc, replacing with Ariel equivalent...
Identified routine: free/_free, replacing with Ariel equivalent...
Identified routine: malloc/_malloc, replacing with Ariel equivalent...
Identified routine: free/_free, replacing with Ariel equivalent...
       4      86    1127 omps_list
OMP_PID = 41187
41304
/Users/sstbuild/jenkins/workspace/SST__6.1.0_beta_OutOfSource_MacOSX_10.11_OMPI_1.8_Boost_1.56_clang_700.1.76_mainline/20_20/devel/trunk/test/utilities/timeLimitEnforcer.sh: line 55: [: 41187: binary operator expected
Sat Jan 14 02:41:49 MST 2017
 
I am 41063, I was called from 41016, my parent PID is 41016
No corresponding child named "sst" 
 
 Look for a child named "python"
Identified routine: malloc/_malloc, replacing with Ariel equivalent...
Identified routine: free/_free, replacing with Ariel equivalent...
No corresponding child named "python" 
 
 Look for a child named "valgrind"
No corresponding child named "valgrind" 
 
Sibling is 41067
Kill pid is 41068
  502 41068 41067   0  2:40AM ??         0:46.49 /Users/sstbuild/jenkins/workspace/SST__6.1.0_beta_OutOfSource_MacOSX_10.11_OMPI_1.8_Boost_1.56_clang_700.1.76_mainline/20_20/local/sst-core/bin/sst -n 1 /Users/sstbuild/jenkins/workspace/SST__6.1.0_beta_OutOfSource_MacOSX_10.11_OMPI_1.8_Boost_1.56_clang_700.1.76_mainline/20_20/devel/trunk/sst-elements/src/sst/elements/memHierarchy/Sieve/tests/sieve-test.py
  502 41068 41067   0  2:40AM ??         0:46.49 /Users/sstbuild/jenkins/workspace/SST__6.1.0_beta_OutOfSource_MacOSX_10.11_OMPI_1.8_Boost_1.56_clang_700.1.76_mainline/20_20/local/sst-core/bin/sst -n 1 /Users/sstbuild/jenkins/workspace/SST__6.1.0_beta_OutOfSource_MacOSX_10.11_OMPI_1.8_Boost_1.56_clang_700.1.76_mainline/20_20/devel/trunk/sst-elements/src/sst/elements/memHierarchy/Sieve/tests/sieve-test.py
 It's still there!  (41068)
 Try a "kill -9" 
  502 41068 41067   0  2:40AM ??         0:00.00 (sstsim.x)
Build was aborted
Aborted by Vandyke, John P

**Comment by allevin** [comment]
Very old issue, will not be likely to be recreated
