### ISSUE TITLE
There is a recurrent testing problem on MacOS with left behind excuting stream binaries

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#619]
These executing tasks can soak up cpu cycles such that tests take a factor of ten or more times as much to complete.    This is primarily observed on El Capitan, but that is our principal MacOS test environment.  This task are created by (or for) Ariel, but test Suites other the "Ariel" Suite use Ariel.   (Cannot reproduce the problem on Linux.)

**Comment by nmhamster** [comment]
@jpvandy - was this the result of the Messier failures?

**Comment by jpvandy** [comment]
Currently suppressed with supplemental clean-up code in the Ariel and memHSieve suites.

**Comment by jpvandy** [comment]
Does the problem still exist?

**Comment by allevin** [comment]
Need to re-evaluate this with the new test-frameworks.
