### ISSUE TITLE
The trace back script, stackback.py,T fails on COE_RHEL-6 for lack of Python-2.7

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#635]
May 2nd  During EmberSweep #58:
'''
test_EmberSweep_058_238ff71fbe090af2a8d8365cdfe9015f  nt=1
 58 run, 0 have failed
      torus --shape=8x8x8  PingPong iterations=10 messageSize=10000 
~/jenkins/workspace/SST__Nightly_COE_RHEL_6_OMPI-1.8_Boost-1.56_mainline_gcc-4.8.2/526_526/devel/trunk/test/testSuites/emberSweep_folder ~/jenkins/workspace/SST__Nightly_COE_RHEL_6_OMPI-1.8_Boost-1.56_mainline_gcc-4.8.2/526_526/devel/trunk
 
TL Enforcer:            TIME LIMIT     test_EmberSweep_058_238ff71fbe090af2a8d8365cdfe9015f 
TL Enforcer: test has exceed alloted time of 900 seconds.
         Create Time Limit Flag file, /tmp/TimeFlag_7637_10133
 
I am 10133, I was called from 7637, my parent PID is 7670
UID         PID   PPID  C STIME TTY          TIME CMD
sstbuild   7637  98256  0 05:07 ?        00:00:00 /bin/bash /home/sstbuild/jenkins/workspace/SST__Nightly_COE_RHEL_6_OMPI-1.8_Boost-1.56_mainline_gcc-4.8.2/526_526/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
sstbuild   7670   7637  0 05:07 ?        00:00:00 /bin/bash /home/sstbuild/jenkins/workspace/SST__Nightly_COE_RHEL_6_OMPI-1.8_Boost-1.56_mainline_gcc-4.8.2/526_526/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
 
sstbuild  10255  10133  0 05:41 ?        00:00:00 grep ompsievetest
 this might better go in the Suite
0 0 0 /tmp/10133_omps_list
OMP_PID = 
Tue May  2 05:41:52 MDT 2017
 
Kill pid is 10136
 
          Invoke the traceback routine 
$SST_ROOT/test/utilities/stackback.py 10136

/usr/bin/env: python2.7: No such file or directory
 
Tue May  2 05:41:52 MDT 2017
   Return to timeLimitEnforcer
 
sstbuild  10136   7670  0 05:26 ?        00:00:01 sst -n 1 --model-options=--topo=torus --shape=8x8x8  --cmdLine="Init" --cmdLine="PingPong iterations=10 messageSize=10000 " --cmdLine="Fini" emberLoad.py
sstbuild  10136   7670  0 05:26 ?        00:00:01 sst -n 1 --model-options=--topo=torus --shape=8x8x8  --cmdLine="Init" --cmdLine="PingPong iterations=10 messageSize=10000 " --cmdLine="Fini" emberLoad.py
 It's still there!  (10136)
 Try a "kill -9" 
/home/sstbuild/jenkins/workspace/SST__Nightly_COE_RHEL_6_OMPI-1.8_Boost-1.56_mainline_gcc-4.8.2/526_526/devel/trunk/test/testTempFiles/bashIN: line 343: 10136 Killed                  sst -n 1 --model-options="--topo=torus --shape=8x8x8  --cmdLine=\"Init\" --cmdLine=\"PingPong iterations=10 messageSize=10000 \" --cmdLine=\"Fini\"" emberLoad.py > tmp_file
 Time Limit detected at 900 seconds
shunit.ASSERT:  Time Limit detected at 900 seconds
~/jenkins/workspace/SST__Nightly_COE_RHEL_6_OMPI-1.8_Boost-1.56_mainline_gcc-4.8.2/526_526/devel/trunk
         -------
'''

**Comment by allevin** [comment]
Very old issue, not likely to be reproduced.
