### ISSUE TITLE
The deadlock determing code, from Branden is not supported on El Capitan and most VMs

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#636]
On El Capitan, it is not being called with the pid of SST

On Linux, Red Hat 6, etal,  The VM does not have Python 2.7, which is required by the script.

**Comment by jpvandy** [comment]
The code is in devel, but non-functional on El Capitan.  See Issue #655

**Comment by allevin** [comment]
Deadlock code is obsolete
