### ISSUE TITLE
The 2x2 test run on Ubuntu 16.04 is a mess of time-limits

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#637]
Needs to be characterized and understood.

**Comment by jpvandy** [comment]
Last run was May 3rd

**Comment by jpvandy** [comment]
2x2  (2 threads and 2 ranks)  can't run reasonable on a VM with too few cores

**Comment by jwilso** [comment]
Might be a runaway powerd daemon on the server again.  ☹

J.

--
Jon Wilson
SST Software Engineering/Quality Assurance
CSRI
Sandia National Laboratories
