### ISSUE TITLE
Valgrind MemHSieve test hung

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#639]
the test was manually killed after 12 hours.   The test normally takes approximately 135 seconds.

The test, memHSieve is known to get occasional time limits.   This case is an unacceptable failure of the time limit enforcer.
Here's the log file:
[Capture-time-limit-May8.txt](https://github.com/sstsimulator/sst-sqe/files/987158/Capture-time-limit-May8.txt)

**Comment by jpvandy** [comment]
Incomplete answer:   It appears that the key is a ompsievetest task left around that ps says belongs to user 1.   It's presence seems to inhibit the Suite from terminating.  I fear there are many edge cases to cleaning this up.

**Comment by allevin** [comment]
Valgrind tests are no longer being run.  closing
