### ISSUE TITLE
All Nighty tests failing from time out on git clone of Elements.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#640]
This showed up Thursday the 4th or Friday the 5th.

This has been addressed by changing the timeout from 90 seconds to 250 seconds.

The next level of relief will be to have the Jenkins runs do "shallow" clones, which will cut the time from two plus minutes to on the order of 17 seconds.

@nmhamster

**Comment by jwilso** [comment]
The proper fix is not to clone multiple times per job, but to instead pull updates to already-cloned repositories. It is unnecessary and wasteful to clone a repository and its entire history each time, cloning should happen only once.
