### ISSUE TITLE
The trace-back code after a time limit is not support on some builders

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#645]
See Elements issue #655.
The trace-back script explicitly requires Python-2.7, which is not the version included in the release on COE-RHEL-6.
@bjmoor 
@jwilso 
The trace-back invocation is still not handled correctly on the timeLimitEnforcer on El Capitan.  (And that's my problem to deal with.)

**Comment by jpvandy** [comment]
June 18th there were Nightly failures on both COE-RHEL-6  VM and on the CentOS 6.6 VM where trace-back was appropriate.   Need to confirm that Python 2.7 is required.   The script seems to work well on CentOS-7  (sst-test) where Python 2.7.5 is the release version.
Just examined output from using Python 2.6 in the trace back on COE_RHEL_6 with a shortened time limit.
My log file cut-and-paste only captured the first 4048 lines of test output.  That contained 182 lines with “test” at the beginning and 58 lines containing “ASSERT” and 29 lines reporting, “Failed to parse any stack for pid” <pid>.
Assumed analysis:
182 tests
29 time limits (58/2)
29 failures.
Conclusion: The trace-back script, as is, requires Python 2.7

**Comment by allevin** [comment]
RHEL6 machine will soon be retired.  Closing.
