### ISSUE TITLE
Ember Sweep time limit hang

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#650]
Time limit on Ember Sweep test 80 on El Capitan, number of ranks=2,  run #445.
This resulted in a hang, which I believe is a SQE problem, not an Ember problem.
"""
test_EmberSweep_080_a23d85edc49a8319faea14f6104ed70b   nr=2
 80 run, 0 have failed
      torus --shape=2  PingPong iterations=1 messageSize=0 
~/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/emberSweep_folder ~/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk
Simulation is complete, simulated time: 4.12 us
 
Test Passed
80: Wall Clock Time  1 sec.   torus --shape=2  PingPong iterations=1 messageSize=0 
 
~/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk
 
TL Enforcer:            TIME LIMIT     test_EmberSweep_080_a23d85edc49a8319faea14f6104ed70b 
TL Enforcer: test has exceed alloted time of 900 seconds.
         Create Time Limit Flag file, /tmp/TimeFlag_10676_28931
 
I am 28931, I was called from 10676, my parent PID is 10709
  UID   PID  PPID   C STIME   TTY           TIME CMD
  502 10676 73706   0  4:29AM ??         0:00.02 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 10709 10676   0  4:29AM ??         0:01.05 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
 
  502 54817 28931   0  4:54AM ??         0:00.00 grep ompsievetest
 this might better go in the Suite
       0       0       0 /tmp/28931_omps_list
OMP_PID = 
Thu May 18 04:54:31 MDT 2017
 
 ###############################################################
  JOHNS sanity check
  502 54769 53884   0  4:54AM ??         0:00.04 mpirun -np 2 -map-by numa:pe=2 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=no /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
  502 54770 54769   0  4:54AM ??         0:00.56 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=no /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
  502 54771 54769   0  4:54AM ??         0:00.55 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=no /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
 ----------- first
  502 54770 54769   0  4:54AM ??         0:00.59 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=no /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
 ----------- all  
  502 54770 54769   0  4:54AM ??         0:00.63 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=no /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
  502 54771 54769   0  4:54AM ??         0:00.62 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=no /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
54770
 the pid of an sst is 54770 
 the pid of the mpirun is 54769 
 Check for Dead Lock
/Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testOutputs/test_ember_params.out:[0:0] SST Core: Signal handers will be registed for USR1, USR2, INT and TERM...
/Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testOutputs/test_ember_params.out:[0:0] SST Core: Signal handler registration is completed
/Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testOutputs/test_ember_params.out:[1:0] SST Core: Signal handers will be registed for USR1, USR2, INT and TERM...
/Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testOutputs/test_ember_params.out:[1:0] SST Core: Signal handler registration is completed
 ###############################################################
I am 28931, I was called from 10709, my parent PID is 10709
No corresponding child named "sst" 
 
 Look for a child named "python"
No corresponding child named "python" 
 
 Look for a child named "valgrind"
No corresponding child named "valgrind" 
 
Sibling is 28944
I am 28931, I was called from 28944, my parent PID is 10709
No corresponding child named "sst" 
 
 Look for a child named "python"
No corresponding child named "python" 
 
 Look for a child named "valgrind"
No corresponding child named "valgrind" 
 
Kill pid is
 
ps: option requires an argument -- p
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
          Invoke the traceback routine 
$SST_ROOT/test/utilities/stackback.py 

Must specify PIDs of SST, or specify --all to find SST PIDs
Use --help for more information
 
Thu May 18 04:54:41 MDT 2017
   Return to timeLimitEnforcer
 
 Can not find process to terminate,  pid =  
     I am 28931,   my parent was 10709
  UID   PID  PPID   C STIME   TTY           TIME CMD
  502 10676 73706   0  4:29AM ??         0:00.02 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 10709 10676   0  4:29AM ??         0:01.05 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 12818 20000   0  4:10AM ??         0:00.01 /bin/sh -xe /var/folders/k7/n40w4cyj4_l78z_fw6677ccm0000gp/T/hudson2016493627556830810.sh
  502 12824 12818   0  4:10AM ??         0:00.31 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
  502 14313     1   0  4:31AM ??         0:01.14 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
  502 19951     1   0 Tue10AM ??         0:03.43 /usr/sbin/cfprefsd agent
  502 20000     1   0 Tue10AM ??         4:49.19 /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -jar /Users/sstbuild/jenkins/slave.jar -jnlpUrl https://jenkins-srn.sandia.gov:8443/computer/SST%20Mac%20OSX%2010.11%20Xcode%207%20(2)/slave-agent.jnlp -secret 17e052036837b2f06631093b7f59eddc3a336352a67333231e5e10768feceaa2
  502 28931 10709   0  4:39AM ??         0:00.05 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 28944 10709   0  4:39AM ??         0:00.00 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 28945 28944   0  4:39AM ??         0:00.00 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_Multi_Rank_ElCapitan_full_n-2/445_445/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 28946 28944   0  4:39AM ??         0:00.00 awk { if ( $3 == ENVIRON["__timerChild"] ) print $2 }
    0 28947 28945   0  4:39AM ??         0:00.00 ps -ef -u sstbuild
  502 29431 73574   0  4:39AM ??         0:00.03 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_MultiThread_MacOS-n2/594_594/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 29458 29431   0  4:39AM ??         0:01.49 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_MultiThread_MacOS-n2/594_594/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 53498     1   0  2:04AM ??         0:47.20 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
  502 53499     1   0  2:04AM ??         0:45.98 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
  502 53500     1   0  2:04AM ??         0:41.20 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
  502 53501     1   0  2:04AM ??         0:46.84 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
  502 53504     1   0  2:04AM ??         0:40.47 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
  502 53820 12824   0  4:54AM ??         0:00.02 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
  502 53884 53820   0  4:54AM ??         0:00.07 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
  502 54896 29458   0  4:54AM ??         0:00.01 /bin/bash /Users/sstbuild/jenkins/workspace/SST__Nightly_MultiThread_MacOS-n2/594_594/devel/trunk/test/testSuites/testSuite_EmberSweep.sh
  502 54899 29458   0  4:54AM ??         0:11.17 sst -n 2 --model-options=--topo=fattree --shape=9,9:9,9:18  --cmdLine="Init" --cmdLine="AllPingPong iterations=10 messageSize=10000 " --cmdLine="Fini" emberLoad.py
  502 54900 54896   0  4:54AM ??         0:00.00 sleep 900
  502 55035 53884   0  4:54AM ??         0:00.01 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
  502 55037 55035   0  4:54AM ??         0:00.00 sleep 200
  502 55040 53884   0  4:54AM ??         0:00.05 mpirun -np 2 -map-by numa:pe=2 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=yes /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
  502 55041 55040   0  4:54AM ??         0:01.96 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=yes /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
  502 55042 55040   0  4:54AM ??         0:01.96 /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/local/sst-core/bin/sst --model-options --TraceType=text --UseDramSim=yes /Users/sstbuild/jenkins/workspace/SST__7.0.0_beta_Multi_Rank_ElCapitan_full_n-2/16_16/devel/trunk/sst-elements/src/sst/elements/prospero/tests/array/trace-common.py
    0 55126 28931   0  4:54AM ??         0:00.00 ps -f -U sstbuild
  502 60675     1   0 Tue11AM ??         0:00.13 /usr/sbin/distnoted agent
  502 62995     1   0 Tue11AM ??         0:00.22 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdflagwriter
  502 72773     1   0 Tue11AM ??         0:00.23 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker-sizing -c MDSSizingWorker -m com.apple.mdworker.sizing
  502 73568 20000   0  4:05AM ??         0:00.01 /bin/sh -xe /var/folders/k7/n40w4cyj4_l78z_fw6677ccm0000gp/T/hudson6215251261761081075.sh
  502 73574 73568   0  4:05AM ??         0:00.16 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
  502 73700 20000   0  4:05AM ??         0:00.01 /bin/sh -xe /var/folders/k7/n40w4cyj4_l78z_fw6677ccm0000gp/T/hudson6861595538799566695.sh
  502 73706 73700   0  4:05AM ??         0:00.22 /bin/bash ../sqe/buildsys/bamboo.sh sstmainline_config_macosx_no_gem5 openmpi-1.8 boost-1.56 clang-700.1.76
  502 98283     1   0  4:24AM ??         0:01.11 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
  502 98648     1   0  4:24AM ??         0:02.03 /System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared
 
                EXIT without killing my parents 
Build was aborted
Aborted by Vandyke, John P
"""

**Comment by allevin** [comment]
Old issue, not likely to be reproduced
