### ISSUE TITLE
Is the SST core supposed to require MPI to build?

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#672]
The Nightly test, Nightly_memH_without openMP, loads openmp-1.8 and the core fails to configure without it.

That appears to be the only current Jenkins project which considers the issue.

I find evidence in December of 2016 for building the core without mpi

(There is a bamboo.sh Scenario, sstmainline_config_no_mpi.)

**Comment by bjmoor** [comment]
SST does NOT require MPI to compile.   At one point, it was decided that the default is to require MPI, unless '--disable-mpi' is passed to `./configure`

**Comment by jpvandy** [comment]
Totally Wrong understanding on my part
