### ISSUE TITLE
Unexplained hang in multi rank El Capitan on simplestats test

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#675]
It appears that the Suite had verified the correctness of the sst run, but the time limit processor fired and the El Capitan timeLimitEnforcer logic some how hung.   
It is known that there are problems with the tLE logic on El Capitan, but nothing like this has been previously observed.

It is not clear exactly where in the test Suite the hang occurred.
Have added a elapsed time print at the end of the test in the Suite. 

The log of the June 27th run is attached.
[MacOS-TL-hang.txt](https://github.com/sstsimulator/sst-sqe/files/1106320/MacOS-TL-hang.txt)

**Comment by allevin** [comment]
Old issue - not likely to be recreated.
