### ISSUE TITLE
invokeSuite edge-case to beware of

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#689]
In specifying multi- thread or rank, the script is assuming that the input Suite is unmodified with respect to number of threads and number of ranks.

In my view, the intention was that specification of number of threads and or cores on the command line of invokeSuites would be honored.    There are edge-cases in which this is not so.  For example, if the environment variable, SST_MULTI_THREAD_COUNT is set, it may interfere with invokeSuites specification.

@allevin  There is no problem with current Autotester usage. 

Plan at the moment is 
(1) to have invokeSuites always write to stdout the image of the command line that invokes sst.
(2)  Have the script look for conflicts and, at least, put out warnings.

**Comment by allevin** [comment]
Not going to be addressed due to migration to new test frameworks.
