### ISSUE TITLE
in Bamboo.sh, failure to find the command, module, does not return error flag.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#7]
An error message is written to stderr, but script execution continues.   ModuleEx detects when "module" does not find the desired specific module, but if the command module is not found or execute correctly no error code is returned.

Sample log output:
OpenMPI (openmpi-1.8) selected
/home/jwilso/jenkins/workspace/memH_without_openMP/7_7/devel/trunk/test/utilities/moduleex.sh: line 26: module: command not found
/home/jwilso/jenkins/workspace/memH_without_openMP/7_7/devel/trunk/test/utilities/moduleex.sh: line 26: module: command not found
bamboo.sh: Boost 1.56 selected

**Comment by allevin** [comment]
@e10harvey, Not sure if this if fixed if it is, please advise so we can close the issue.
