### ISSUE TITLE
Unnecessary inconstancy in name of Detailed Network output vs. reference File

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#703]
The reference file is named consistantly with most output / reference File:
test_scheduler_DetailedNetwork.out.

The output file generated by SQE omits the "scheduler".

The test Suite is "test scheduler_DetailedNetwork.sh"

**Comment by jpvandy** [comment]
Problem is much worse.  The test Suite was referencing the SQE version of the Reference file rather than the appropriate one in the elements sub-tree

**Comment by allevin** [comment]
Scheduler is deprecated and will go away in SST 11 - Wont fix.
