### ISSUE TITLE
Need regression testing of the time limit enforcer

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#754]
Time Limit processing for the Nightly testing has evolved in response to changing needs as tests have become much more complex than just requiring a match to gold file.   This evolution has suffered from point solutions to the needs of new tests.  SST testing has evolved to the extent that a point solution to the latest edge case, may interfere with what's done for some previous edge case.

**Comment by allevin** [comment]
Not going to be addressd due to Migration to new test frameworks
